Repository EGC2425-RaboDeToro-hub/RaboDeToro-hub-1, pull requests merged in 2024-12, with the labels that each got.

#44 test: Añadir pruebas para la función mejorar búsqueda
  docs/Definicion de procesos.pdf
  docs/Moreno-RaboDeToro-hub1.pptx
  flask_session/04b4241d607265515cd3f822b60a0585
  flask_session/204a0344da3c91c178acce5ae7e3accf
  flask_session/27139141ba9b4bb866d5e297ccda18ed
  flask_session/286f62323e50418e9489bb06c37409a4
  flask_session/2a2801a4d4097af0ab1af3225237ec8b
  flask_session/2baf7487e1d3d3e21903c825e4e8cbc1
  flask_session/355eda51b8e8f397b9629f8406716e58
  flask_session/552510e84f64dddd3b39bc95c67c0df9
  flask_session/61c32fd99f6791013e24b1cebbdfb396
  flask_session/782e2b1c07ed4f185d9dc513c8f8432f
  flask_session/84f512685f1300022cfed7afbcc086e8
  flask_session/8f420506d7c63a7630537bf3ce438407
  flask_session/a49e6eb2c9c686b46ef73d4aecec09d0
  flask_session/a4bfcad0c5fafcc1bff60ecf7543fd63
  flask_session/b3ed7b868b6801d782d849274e2c3494
  flask_session/bfdf18809d69a6c2a7e31d141a3aba92
  flask_session/c2659106d82ffb4583d53ef0451af707
  flask_session/c4b9f276628b047807f66fd8d141fde9
  flask_session/c61855b664d372f401802438d8076f10
  flask_session/d1bf4a847fc7b08de9e8eb9b6e2024af
  flask_session/db189f684e2963e775700f40459d5677
  flask_session/e731ca088278f940b3ef419283822e06
  flask_session/fe32fd57a7db197be4b8b42911cf2588
Labels: medium Priority, test

#47 feat: Añadir plantillas issue
  .github/ISSUE_TEMPLATES/issue_technical_task_template.yml
  .github/ISSUE_TEMPLATES/issue_work_item_template.yml
Labels: high Priority

#49 Update README.md
  README.md
Labels: documentation

#50 style: lint limpiado
  .gitignore
  app/modules/auth/routes.py
  app/modules/dataset/api.py
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_integration.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/email/services.py
  app/modules/explore/repositories.py
  app/modules/explore/routes.py
  app/modules/explore/tests/test_unit.py
  app/modules/forgotPassword/models.py
  app/modules/forgotPassword/routes.py
  app/modules/forgotPassword/services.py
  app/modules/profile/routes.py
Labels: add, low Priority

#51 docs: Acta Fundacional
  docs/ActaFundacional.pdf
Labels: documentation, medium Priority

#57 test: community tests
  app/modules/community/tests/test_integration.py
  app/modules/community/tests/test_selenium.py
Labels: medium Priority, test

#60 feat: Añadir automatización de pruebas
  run_rosemary_test.py
Labels: medium Priority, test

#62 test: Test de comunidad arreglados
  app/modules/community/tests/test_selenium.py
Labels: low Priority, test

#64 fix: Arreglar workflow
  .github/workflows/commit.yml
Labels: bug

#65 docs: Actualizar Readme
  README.md
Labels: documentation

#66 docs: Definición de procesos
  docs/Definicion de procesos.pdf
Labels: documentation

#67 fix: FIx the function extract_token_from_email
  app/modules/forgotPassword/tests/locustfile.py
Labels: bug

#68 style: Eliminar .vscode
  .vscode/settings.json
Labels: low Priority

#70 Feature/personalizacion de scripts/69
  .env.vagrant.example
  .gitignore
  README.md
  app.log.1
  app/__init__.py
  app/modules/forgotPassword/tests/locustfile.py
  app/modules/forgotPassword/tests/test_integration.py
  app/modules/forgotPassword/tests/test_selenium.py
  app/modules/profile/routes.py
  core/managers/logging_manager.py
  flask_session/04b4241d607265515cd3f822b60a0585
  flask_session/0a1768e3f9329b2479473a1df906c0e8
  flask_session/19eeeab780f1c01d506362687871f936
  flask_session/1d1e4f1889eb35498d383dbb3c0f7ecb
  flask_session/1f3539317e08004c130d62963282f499
  flask_session/2029240f6d1128be89ddc32729463129
  flask_session/204a0344da3c91c178acce5ae7e3accf
  flask_session/21b2d3fcbd05af1ff7cf314f56a9495b
  flask_session/25413647ffb3e709951940adb3239686
  flask_session/27139141ba9b4bb866d5e297ccda18ed
  flask_session/286f62323e50418e9489bb06c37409a4
  flask_session/2a2801a4d4097af0ab1af3225237ec8b
  flask_session/2baf7487e1d3d3e21903c825e4e8cbc1
  flask_session/355eda51b8e8f397b9629f8406716e58
  flask_session/552510e84f64dddd3b39bc95c67c0df9
  flask_session/5c6f76f87b94af9648ff15a85e82d804
  flask_session/5df536df18dc051af4883187876f91d4
  flask_session/5f69ffb52f8ab850bd706b0b35395b07
  flask_session/61c32fd99f6791013e24b1cebbdfb396
  flask_session/6e6bfcc190444f21f239bb782eef3742
  flask_session/782e2b1c07ed4f185d9dc513c8f8432f
  flask_session/84f512685f1300022cfed7afbcc086e8
  flask_session/8f420506d7c63a7630537bf3ce438407
  flask_session/8fd0af50569b7c6a4e00f70e3fc85f88
  flask_session/a49e6eb2c9c686b46ef73d4aecec09d0
  flask_session/a4bfcad0c5fafcc1bff60ecf7543fd63
  flask_session/aef2d1a270231b26577b43ae332a40fb
  flask_session/b3ed7b868b6801d782d849274e2c3494
  flask_session/b6b1a69e17440536e96f0a6174e9a558
  flask_session/bf05b76e2a76b7aef9b43a6ee2bd1b72
  flask_session/bfdf18809d69a6c2a7e31d141a3aba92
  flask_session/c15c2f584abc366750f5077ca5970c12
  flask_session/c2659106d82ffb4583d53ef0451af707
  flask_session/c4b9f276628b047807f66fd8d141fde9
  flask_session/c5003fe75632356d50c744ae3586662f
  flask_session/c61855b664d372f401802438d8076f10
  flask_session/d1bf4a847fc7b08de9e8eb9b6e2024af
  flask_session/db189f684e2963e775700f40459d5677
  flask_session/e731ca088278f940b3ef419283822e06
  flask_session/fa304659ef89f9bf4531199d4aabecdc
  flask_session/fe32fd57a7db197be4b8b42911cf2588
  setup.sh
Labels: CD, add, low Priority

#73 fix: fakenodo
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/services.py
  app/modules/fakenodo/tests/locustfile.py
  app/modules/fakenodo/tests/test_selenium.py
  app/modules/fakenodo/tests/test_unit.py
  app/modules/zenodo/services.py
Labels: hard, add, fakenodo

#76 fix: vagrant
  vagrant/02_install_mariadb.yml
Labels: CI, add, medium Priority

#75 fix: Arreglar workflows
  .github/workflows/codacy2.yml
  .github/workflows/render.yml
Labels: bug, workflows

#80 fix: Arreglar workflow
  .github/workflows/commit.yml
Labels: bug, medium

#81 fix: Arreglar workflow
  .github/workflows/commit.yml
Labels: bug, medium

#82 Update setup.sh
  README.md
  setup.sh
Labels: CI

#84 fix: Corregir weebkook
  .github/hooks/commit-msg
Labels: CI

#85 test: fakenodo.
  app/modules/fakenodo/services.py
  app/modules/fakenodo/tests/test_unit.py
Labels: test

#87 fix: 55%cov
  app/modules/community/seeders.py
  app/modules/email/seeders.py
  app/modules/fakenodo/forms.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/seeders.py
  app/modules/fakenodo/tests/test_integration.py
  app/modules/fakenodo/tests/test_unit.py
  app/modules/featuremodel/seeders.py
  app/modules/flamapy/seeders.py
  app/modules/forgotPassword/seeders.py
  app/modules/hubfile/seeders.py
  app/modules/notepad/seeders.py
  app/modules/webhook/seeders.py
Labels: test

#89 docs: Actualizar procesos
  docs/Definicion de procesos.pdf
Labels: documentation, add

#90 docs: Modificar README
  README.md
  app/modules/auth/tests/test_selenium_ide/test_signup.py
Labels: documentation

#93 Hotfix/download all dataset/6
  app/modules/dataset/services.py
  app/modules/dataset/tests/test_unit.py
Labels: bug, add, medium, test

#94 fix: FIltro avanzado
  app/modules/dataset/api.py
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_integration.py
  app/modules/dataset/tests/test_unit.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/routes.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_integration.py
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_unit.py
  scripts/update_columns.py
Labels: bug, hard, test

#91 Develop
  README.md
  app/modules/auth/tests/test_selenium_ide/test_signup.py
  app/modules/dataset/api.py
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_integration.py
  app/modules/dataset/tests/test_unit.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/routes.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_integration.py
  app/modules/explore/tests/test_selenium.py
  app/modules/explore/tests/test_unit.py
  docs/ActaFundacional.pdf
  docs/Definicion de procesos.pdf
  scripts/update_columns.py
Labels: add

#95 fix: explore tests
  app/modules/explore/tests/test_selenium.py
Labels: test

#96 fix: Modificar seeders
  app/modules/dataset/seeders.py
Labels: bug, hard

#100 fix= Arreglar mail
  .env.local.example
  app/modules/email/services.py
Labels: bug

#106 fix: Arreglo listado dataset
  app/modules/dataset/templates/dataset/list_datasets.html
Labels: bug

#109 Develop
  .env.local.example
  app/modules/dataset/seeders.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/email/services.py
  app/modules/explore/tests/test_selenium.py
Labels: add

#114 feat: Añadir test upload
  app/modules/dataset/tests/test_selenium.py
Labels: test

#118 fix: arreglar env
  .env.local.example
  README.md
Labels: bug

#119 fix: Update render.yml
  .github/workflows/render.yml
Labels: add

#117 Develop
  .env.local.example
  app/modules/dataset/tests/test_selenium.py
  migrations/versions/7473c406f67e_eliminar_columnas_size_in_kb_feature_.py
  migrations/versions/a774749602b7_.py
  migrations/versions/dda763e701cd_añadir_columnas_físicas_feature_count_.py
  setup.sh
Labels: bug, add

#130 fix: setup
  setup.sh
Labels: bug, CD

#134 style: Cambiar titulo
  app/modules/public/templates/public/index.html
Labels: bug, low Priority

#135 feat: Develop
  app/modules/public/templates/public/index.html
Labels: add, low Priority
